version: "3"
services: 
  mongo: 
    environment: 
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_USERNAME: root
    image: mongo
    restart: always
    volumes: 
      - ../database/data:/data/db:rw
    ports: 
      - 27017:27017
  mongo-express: 
    environment: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
    image: mongo-express
    ports: 
      - 8081:8081
    restart: always
    depends_on: 
      - mongo
  # Geant: 
  #   container_name: geant_crawler
  #   build: 
  #     context: ../ProductCrawler
  #     dockerfile: Dockerfile
  #   image: scrapy:latest
  #   command: ./scripts/docker-spider-entrypoint.sh
  #   environment: 
  #     CONTAINER_SCRIPT: Geant
  #   depends_on: 
  #     - mongo

  # Livrini: 
  #   container_name: livrin_crawler
  #   image: scrapy:latest
  #   command: ./scripts/docker-spider-entrypoint.sh
  #   environment: 
  #     CONTAINER_SCRIPT: livrini
  #   depends_on: 
  #     - mongo
  
  # MonoPrix: 
  #   container_name: monoprix_crawler
  #   image: scrapy:latest
  #   command: ./scripts/docker-spider-entrypoint.sh
  #   environment: 
  #     CONTAINER_SCRIPT: MonoPrix
  #   depends_on: 
  #     - mongo
    